### Raiz da aplicação
GET http://localhost:5081/

### Testar a segunda funcionalidade
GET  http://localhost:5081/api/produto/listar

### Buscar produto por nome
GET  http://localhost:5081/api/produto/buscar/TV
###Cadastrar produto 
POST http://localhost:5081/api/produto/cadastrar
Content-Type: application/json

{
    "nome" : "TV",
    "quantidade" : 324,
    "preco" : 678.89
}

###Remover produto
DELETE http://localhost:5081/api/produto/remover/9ada501f-3792-4c5f-a010-112f908b9a52

###Alterar produto

PATCH http://localhost:5081/api/produto/editar/4395194b-107e-4315-b393-02a0bc99254c
Content-Type: application/json

{
    "nome" : "Microondas",
    "quantidade" : 324,
    "preco" : 678.89
}
